SELECT * FROM Receta
SELECT * FROM Detalle_Receta
SELECT * FROM Detalles_Pedido
SELECT * FROM Owner_Restaurante
SELECT * FROM Restaurante
SELECT * FROM Recibo
SELECT * FROM Detalles_Pedido
SELECT * FROM Ingredientes
SELECT * FROM Usuario
SELECT * FROM Pedido